name: ZoneCore
version: 1.1
author: iamdansker
main: info.jeppes.ZoneCore.ZoneCorePlugin
load: STARTUP
website: http://www.jeppes.info
#Commands are registrered by the plugin itself dynamically to make it easier to
#add commands and for other developers to add commands
commands:
  zc:
    description: ZoneCore Commands
  zonecore:
    description: ZoneCore Commands
#Plugins developed for the ZoneCore should have this in it's plugin.yml file
#depend: [ZoneCore]